tick_rate = 50
default_channel = "files"
history_size = 200
global_history = false

[ui]
ui_scale = 100
orientation = "landscape"
theme = "default"

[ui.input_bar]
position = "top"
prompt = ">"
border_type = "rounded"

[ui.status_bar]
separator_open = ""
separator_close = ""

[ui.results_panel]
border_type = "rounded"

[ui.preview_panel]
size = 50
scrollbar = true
border_type = "rounded"

[ui.help_panel]
show_categories = true
hidden = true

[shell_integration]
fallback_channel = "files"

[shell_integration.channel_triggers]
"alias" = ["alias", "unalias"]
"env" = ["export", "unset"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = [
  "cat",
  "less",
  "head",
  "tail",
  "vim",
  "nano",
  "bat",
  "cp",
  "mv",
  "rm",
  "touch",
  "chmod",
  "chown",
  "ln",
  "tar",
  "zip",
  "unzip",
  "gzip",
  "gunzip",
  "xz",
]
"git-diff" = ["git add", "git restore"]
"git-branch" = [
  "git checkout",
  "git branch",
  "git merge",
  "git rebase",
  "git pull",
  "git push",
]
"git-log" = ["git log", "git show"]
"git-repos" = ["nvim", "code", "hx", "git clone"]

[shell_integration.keybindings]
"smart_autocomplete" = "ctrl-t"
"command_history" = "ctrl-r"
