general {
  lock_cmd = /run/current-system/sw/bin/pidof hyprlock || @PROFILE_BIN@/hyprlock
  before_sleep_cmd = /run/current-system/sw/bin/loginctl lock-session
  after_sleep_cmd = /run/current-system/sw/bin/hyprctl dispatch dpms on
}

listener {
  timeout = 600
  on-timeout = /run/current-system/sw/bin/loginctl lock-session
}

listener {
  timeout = 900
  on-timeout = /run/current-system/sw/bin/hyprctl dispatch dpms off
  on-resume = /run/current-system/sw/bin/hyprctl dispatch dpms on
}

listener {
  timeout = 3600
  on-timeout = /run/current-system/sw/bin/systemctl suspend
}
