# foot 终端配置

[main]
font=Fira Code:size=13, Maple Mono NF CN:size=13
dpi-aware=no
pad=12x12 center
selection-target=clipboard
login-shell=yes

[scrollback]
lines=100000
multiplier=5

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes

[key-bindings]
scrollback-up-line=Shift+Up
scrollback-down-line=Shift+Down

[colors]
alpha=1.0
foreground=@THEME_FG@
background=@THEME_BG@
cursor=@THEME_BG@ @THEME_FG2@
selection-foreground=@THEME_FG@
selection-background=@THEME_BG2@
urls=@THEME_BLUE@

regular0=@THEME_BG1@
regular1=@THEME_RED@
regular2=@THEME_GREEN@
regular3=@THEME_YELLOW@
regular4=@THEME_BLUE@
regular5=@THEME_PURPLE@
regular6=@THEME_CYAN@
regular7=@THEME_FG1@

bright0=@THEME_BG3@
bright1=@THEME_RED@
bright2=@THEME_GREEN@
bright3=@THEME_YELLOW@
bright4=@THEME_BLUE@
bright5=@THEME_PURPLE@
bright6=@THEME_TEAL@
bright7=@THEME_FG2@
